# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Bump (Main Branch)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [16.x, 18.x]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       name: Use Node.js ${{ matrix.node-version }}
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #     - run: |
  #         npm i
  #         npm run l:bootstrap
  #         npm run l:lint
  #         npm run l:test
  #         npm run l:build

  bump_version:
    # needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - run: |
          npx lerna version patch --yes --loglevel silly --ignore-scripts --no-private --force-publish --message '%s [skip ci]'

# npm run l:bump